### ISSUE TITLE
hpx::cout vs std::cout

### ISSUE THREAD

**Issue by diehlpk** [Jakub-Golinowski/opencv_hpx_backend#2]
https://github.com/Jakub-Golinowski/opencv_hpx_backend/blob/53cd43995421f3958a97bcfe530f93755ccb70f1/hpx_image_load/hpx_image_load.cpp#L75

Is there any reason why you combine std::cout and hpx::cout? I would prefer to be consistent there. 

And I would recommend to use std::endl instead of \n to make it os independent

**Comment by Jakub-Golinowski** [comment]
This code is "built" on top of the resource_partitioner example and the errors were propagated from there.
I am re-opening the issue because I did not see the second line about \n at first. Will take care of that in next commit.

**Comment by msimberg** [comment]
I agree with using  `hpx::cout` over `std::cout`, but as far as I know `\n` is already portable, i.e. it is translated to the correct sequence of `\r` and `\n` on different platforms. `endl` is essentially the same as `"\n" << flush`, and you do not need to flush the output each time you add a newline (depends on the behaviour you want).

**Comment by diehlpk** [comment]
@msimberg Is write and you can keep them.
